version: '3'
services:
    nuxt: &app_base
        build:
            context: .
        environment:
            PORT: 3000
            HOST: 0.0.0.0
        volumes:
            - ./:/opt/app
    workspace:
        <<: *app_base
        ports:
            - "3000:3000"
        command: yarn dev